# Generated by Django 2.2.4 on 2021-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
