# Generated by Django 2.2.4 on 2021-05-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shell_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='dojos',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='shell_app.dojos'),
            preserve_default=False,
        ),
    ]
