# Generated by Django 2.2.4 on 2021-05-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shell_app', '0002_ninjas_dojos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ninjas',
        ),
    ]
