# Generated by Django 2.2.4 on 2021-05-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shell_app', '0003_delete_ninjas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ninjas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='shell_app.dojos')),
            ],
        ),
    ]
